### ISSUE TITLE
new issue found on rpi

### ISSUE THREAD

**Issue by mostafarahim** [paul-pias/Object-Detection-and-Distance-Measurement#22]
python3.5 /home/pi/o/object_detection.py
Traceback (most recent call last):
  File "/home/pi/o/object_detection.py", line 159, in <module>
    ObjectDetection(id).main()
  File "/home/pi/o/object_detection.py", line 89, in __init__
    self.classes = load_classes('data/coco.names')
  File "/home/pi/o/util.py", line 81, in load_classes
    fp = open(namesfile, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco.names'

**Comment by paul-pias** [comment]
The error is implicit. Kindly check the data folder to find coco.names. If it's not there download it and place it there.

**Comment by mostafarahim** [comment]
thank you sir that worked correctly and finally ran out with no error but the output has no detection as you can see

python3.5 /home/pi/o/object_detection.py
Loading network.....
Network successfully loaded
[INFO] elasped time: 4.74
[INFO] approx. FPS: 0.2
[INFO] elasped time: 4.41
[INFO] approx. FPS: 0.2
[INFO] elasped time: 4.45
[INFO] approx. FPS: 0.2
[INFO] elasped time: 5.33
[INFO] approx. FPS: 0.2
[INFO] elasped time: 4.46
[INFO] approx. FPS: 0.2
[INFO] elasped time: 4.11
[INFO] approx. FPS: 0.2
[INFO] elasped time: 4.89
[INFO] approx. FPS: 0.2
[INFO] elasped time: 4.57
[INFO] approx. FPS: 0.2
[INFO] elasped time: 8.39
[INFO] approx. FPS: 0.1
[INFO] elasped time: 7.41
[INFO] approx. FPS: 0.1
